#' Run SPC Chart Test with Advanced Highlighting and Phase Handling
#'
#' This function produces an SPC chart from the data frame generated by `create_spc_data`, using the styling defined in `make_chart`.
#' It highlights points based on various conditions: `sigma.signal`, `shift` sequences, `fifteen_more` long runs, `trend` stability, and `two_more` patterns.
#' If phases are present, it treats each phase as an independent subgroup for applying these highlighting rules.
#'
#' @param data A data frame containing the SPC data including at least the columns 'x' for dates,
#'        'y' for the measurement values, 'cl' for the centerline, 'lcl' for the lower control limit,
#'        'ucl' for the upper control limit, and various signal columns.
#' @param chart_title A character string representing the title of the chart.
#' @param chart_title_size Numeric value defaulted at 14 but can be changed according to need
#' @param caption Character string that can be used to enter the source of the data on the bottom right
#' @param caption_size Numeric value that is defaulted at 8 but can be used to change the size of the caption
#' @param annotations A data frame containing the annotations with columns 'row_number', 'label',
#'        'text_size', 'position_x', 'position_y'. The 'position_x' and 'position_y' columns
#'        specify the offset for the annotation text relative to the point.
#' @return A ggplot object representing the SPC chart with customized aesthetics.
#' @export
#' @importFrom ggplot2 ggplot geom_line geom_point geom_text geom_segment aes labs scale_x_discrete theme_minimal theme element_text element_blank scale_fill_manual
#' @importFrom lubridate parse_date_time
#' @importFrom grDevices rgb
#' @examples
#' data <- create_spc_data(your_data_frame, 'date', 'value', 'xbar')
#' annotations <- data.frame(
#'   row_number = c(10, 20),
#'   label = c("Annotation 1", "Annotation 2"),
#'   text_size = c(4, 4),
#'   position_x = c(1, -1),
#'   position_y = c(10, -10)
#' )
#' plot_test_spc_chart(data, "Comprehensive Monthly SPC Chart", annotations = annotations)
plot_test_spc_chart <- function(data, chart_title = "", chart_title_size = 14, caption = "", caption_size = 8, annotations = NULL) {
  # Ensure 'x' is a Date object
  if (!inherits(data$x, "Date")) {
    data$x <- parse_date_time(data$x, orders = c("ymd_HMS", "ymd_HM", "ymd_H",
                                                 "mdy_HMS", "mdy_HM", "mdy_H", "mdy",
                                                 "dmy_HMS", "dmy_HM", "dmy_H", "dmy",
                                                 "ydm_HMS", "ydm_HM", "ydm_H", "ydm",
                                                 "ym"))
    if (!inherits(data$x, "Date")) {
      data$x <- as.Date(data$x)
    }
  }
  data$x <- as.character(data$x)  # Convert dates to character for categorical plotting

  # Define color palette
  colors <- list(
    y = rgb(74, 121, 134, maxColorValue = 255),
    cl = rgb(216, 159, 62, maxColorValue = 255),
    lcl_ucl = rgb(190, 190, 190, maxColorValue = 255),
    title = rgb(27, 87, 104, maxColorValue = 255),
    annotation = rgb(40, 40, 40, maxColorValue = 255),
    annotation_line = rgb(169, 169, 169, maxColorValue = 255),
    special = rgb(255,182,193, maxColorValue = 255),
    shift_pattern = rgb(195,100,77, maxColorValue = 255),
    fifteen_more = rgb(197, 92, 217, maxColorValue = 255),
    trend_stability = rgb(77,134,195, maxColorValue = 255),
    normal = rgb(255, 255, 255, maxColorValue = 255),
    two_of_three = rgb(58, 163, 38, maxColorValue = 255)
  )

  # Split data by phase
  data_list <- split(data, data$phase)

  # Function to apply highlighting rules within each phase
  apply_highlighting <- function(df) {
    # Default condition names and colors
    fill_conditions <- rep("Normal", nrow(df))
    fill_colors <- rep(colors$normal, nrow(df))

    # Sigma Signal
    fill_conditions[df$sigma.signal] <- "Sigma Signal"
    fill_colors[df$sigma.signal] <- colors$special

    # Shift patterns
    rle_shift <- rle(df$shift)
    pos <- 1
    for (i in seq_along(rle_shift$lengths)) {
      if (!is.na(rle_shift$values[i]) && rle_shift$lengths[i] >= 8) {
        indices <- pos:(pos + rle_shift$lengths[i] - 1)
        fill_conditions[indices] <- "Shift"
        fill_colors[indices] <- colors$shift_pattern
      }
      pos <- pos + rle_shift$lengths[i]
    }

    # Fifteen or more points in a run
    if ("fifteen_more" %in% names(df) && any(df$fifteen_more, na.rm = TRUE)) {
      rle_fifteen <- rle(df$fifteen_more)
      pos <- 1
      for (i in seq_along(rle_fifteen$lengths)) {
        if (rle_fifteen$values[i] && rle_fifteen$lengths[i] >= 15) {
          indices <- pos:(pos + rle_fifteen$lengths[i] - 1)
          fill_conditions[indices] <- "15+"
          fill_colors[indices] <- colors$fifteen_more
        }
        pos <- pos + rle_fifteen$lengths[i]
      }
    }

    # Trend analysis
    differences <- c(diff(df$y), NA)
    trends <- ifelse(differences < 0, TRUE, ifelse(differences > 0, FALSE, NA))
    rle_trend <- rle(trends)
    pos <- 1
    for (i in seq_along(rle_trend$lengths)) {
      if (rle_trend$lengths[i] >= 5) {
        indices <- pos:(pos + rle_trend$lengths[i] - 1)
        if (length(differences) >= max(indices) + 1) {
          indices <- c(indices, max(indices) + 1)
        }
        fill_conditions[indices] <- "Trend"
        fill_colors[indices] <- colors$trend_stability
      }
      pos <- pos + rle_trend$lengths[i]
    }


    # Two out of three rule
    for (i in 3:nrow(df)) {
      if (sum(df$two_more[(i-2):i], na.rm = TRUE) >= 2) {
        if (all(fill_conditions[(i-2):i] == "Normal")) {
          fill_conditions[(i-2):i] <- "Two Out of Three"
          fill_colors[(i-2):i] <- colors$two_of_three
        }
      }
    }

    df$fill_conditions <- fill_conditions
    df$fill_colors <- fill_colors
    return(df)
  }


  # Apply highlighting to each phase
  data_list <- lapply(data_list, apply_highlighting)

  # Combine data back
  highlighted_data <- do.call(rbind, data_list)

  # Create the plot
  p <- ggplot(highlighted_data, aes(x = x, y = y)) +
    lapply(data_list, function(df) {
      list(
        geom_line(data = df, aes(y = cl, group = phase), color = colors$cl, size = 1.25),
        geom_line(data = df, aes(y = lcl, group = phase), color = colors$lcl_ucl, size = 1.25, alpha = 0.5),
        geom_line(data = df, aes(y = ucl, group = phase), color = colors$lcl_ucl, size = 1.25, alpha = 0.5)
      )
    }) +
    geom_line(aes(group = 1), color = colors$y, size = 1.25) +
    geom_point(aes(fill = fill_conditions), shape = 21, size = 3, color = colors$y) +
    scale_fill_manual(values = c(
      "Normal" = colors$normal,
      "Sigma Signal" = colors$special,
      "Shift" = colors$shift_pattern,
      "15+" = colors$fifteen_more,
      "Trend" = colors$trend_stability,
      "Two Out of Three" = colors$two_of_three
    ), name = NULL) +
    labs(title = chart_title) +
    scale_x_discrete(name = "Date", breaks = unique(highlighted_data$x), labels = unique(highlighted_data$x)) +
    theme_minimal(base_family = "sans") +
    theme(
      plot.title = element_text(color = colors$title, size = chart_title_size, hjust = 0.5),
      plot.background = element_blank(),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      legend.position = "bottom",
      axis.title = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, color = "darkgray"),
      axis.text.y = element_text(color = "darkgray"),
      axis.ticks = element_line(color = "darkgray"),
      axis.line = element_line(color = "darkgray"),
      plot.caption = element_text(size = caption_size, color = "darkgray", hjust = 1),
      plot.caption.position = "plot"
    )

  # Conditionally add chart title if provided
  if (chart_title != "") {
    p <- p + labs(title = chart_title)
  }

  # Conditionally add caption if provided
  if (caption != "") {
    p <- p + labs(caption = caption)
  }
  # Conditionally add annotations if provided
  if (!is.null(annotations) && nrow(annotations) > 0) {
    # Add columns to annotations for plotting
    annotations$x <- data$x[annotations$row_number]
    annotations$y <- data$y[annotations$row_number]

    # Convert x to factor to get levels and then to numeric index
    data$x_factor <- factor(data$x, levels = unique(data$x))
    annotations$x_index <- as.numeric(factor(annotations$x, levels = levels(data$x_factor)))

    # Adjust x positions based on position_x
    annotations$label_x <- annotations$x_index + annotations$position_x
    annotations$label_x <- factor(annotations$label_x, levels = seq_along(levels(data$x_factor)))
    annotations$label_x <- levels(data$x_factor)[pmin(pmax(as.numeric(annotations$label_x), 1), length(levels(data$x_factor)))]

    # Adjust starting point of annotation line to be on the border of the data point
    point_radius <- 0.5  # Adjusted for size of the data point
    p <- p +
      geom_segment(data = annotations, aes(x = x, y = y + point_radius, xend = label_x, yend = y + position_y),
                   color = colors$annotation_line, size = 0.5) +
      geom_text(data = annotations, aes(x = label_x, y = y + position_y, label = label),
                color = colors$annotation, size = annotations$text_size, hjust = 0.5, vjust = -0.3)
  }

  return(p)
}
